"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "fr" | "ar"
type Direction = "ltr" | "rtl"

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    dir: Direction
    toggleLanguage: () => void
}

const translations = {
    fr: {
        "common.currency": "MAD",
        "common.size": "Taille",
        "common.color": "Couleur",
        "common.morocco": "Maroc",
        // Navigation
        "nav.shop": "Boutique",
        "nav.collections": "Collections",
        "nav.about": "À propos",
        "nav.faq": "FAQ",
        "nav.search": "Rechercher",
        "nav.shop_now": "Acheter maintenant",
        "nav.view_all_collections": "Voir toutes les collections",

        // Header Popups
        "header.categories": "Catégories",
        "header.browse_by_category": "Parcourir par catégorie",
        "header.face_care": "Soins du visage",
        "header.face_care_desc": "Sérums, crèmes et huiles",
        "header.hair_care": "Soins des cheveux",
        "header.hair_care_desc": "Traitements et masques",
        "header.body_care": "Soins du corps",
        "header.body_care_desc": "Lotions et beurres",
        "header.gift_sets": "Coffrets cadeaux",
        "header.gift_sets_desc": "Sélections spéciales",
        "header.new_arrival": "Nouveautés",
        "header.argan_elixir": "Élixir capillaire à l'argan",
        "header.argan_elixir_desc": "Formule révolutionnaire pour des cheveux soyeux",
        "header.signature": "Signature",
        "header.essentials": "Essentiels",
        "header.premium": "Premium",

        // Hero
        "hero.title_prefix": "Style",
        "hero.title_suffix": "Féminin Sans Effort",
        "hero.subtitle": "Découvrez des vêtements féminins de luxe et de boutique – des essentiels quotidiens aux robes de soirée pour chaque occasion.",
        "hero.shop_collection": "Voir la collection",
        "hero.explore_best_sellers": "Découvrir les meilleures ventes",
        "hero.fast_delivery": "Livraison rapide",
        "hero.secure_checkout": "Paiement sécurisé",
        "hero.easy_returns": "Retours faciles",
        "hero.pure_argan_oil": "Huile d'argan pure",
        "hero.cold_pressed": "Pressée à froid",

        // Sections
        "section.featured_collections": "Collections en vedette",
        "section.featured_desc": "Découvrez nos collections sélectionnées de robes, ensembles et essentiels de garde-robe.",
        "section.best_sellers": "Catégories",
        "section.best_sellers_desc": "Parcourez toutes nos catégories de vêtements.",
        "section.all_categories": "Tout",
        "section.view_all_products": "Voir tous les produits",
        "section.load_more": "Charger plus",
        "section.why_choose": "Pourquoi choisir Azana ?",
        "section.organic": "Tissus premium",
        "section.organic_desc": "Matériaux doux et respirants choisis pour le confort et la durabilité.",
        "section.award_winning": "Coupes flatteuses",
        "section.award_winning_desc": "Silhouettes conçues pour mettre en valeur chaque silhouette.",
        "section.cruelty_free": "Design conscient",
        "section.cruelty_free_desc": "Pièces réfléchies que vous pouvez porter saison après saison.",
        "section.handcrafted": "Détails boutique",
        "section.handcrafted_desc": "Finitions qui rendent chaque look spécial.",
        "section.limited_offer": "Offre limitée",
        "section.promo_title": "25% de réduction sur votre première tenue",
        "section.promo_desc": "Commencez votre garde-robe Azana avec 25% de réduction. Utilisez le code WELCOME25 à la caisse.",
        "section.get_offer": "Obtenir l'offre",
        "section.hurry_up": "Dépêchez-vous !",
        "section.view_collection": "Voir la collection",

        // Newsletter
        "newsletter.title": "Restez à la mode",
        "newsletter.desc": "Abonnez-vous pour des offres exclusives, des conseils de style et un accès anticipé aux nouveautés.",
        "newsletter.placeholder": "Entrez votre email",
        "newsletter.subscribe": "S'abonner",
        "newsletter.disclaimer": "En vous abonnant, vous acceptez notre Politique de confidentialité. Désabonnez-vous à tout moment.",

        // Footer
        "footer.company": "Entreprise",
        "footer.support": "Support",
        "footer.legal": "Légal",
        "footer.our_story": "Notre histoire",
        "footer.sustainability": "Durabilité",


        "footer.contact_us": "Contactez-nous",
        "footer.shipping_info": "Informations de livraison",

        "footer.privacy_policy": "Politique de confidentialité",
        "footer.terms": "Conditions de service",
        "footer.refund_policy": "Politique de remboursement",
        "footer.cookies": "Cookies",
        "footer.rights": "Tous droits réservés.",

        // Product & Cart
        "product.add_to_cart": "Ajouter au panier",
        "product.reviews": "avis",
        "product.in_stock": "En stock",
        "product.out_of_stock": "Rupture de stock",
        "product.select_size": "Sélectionner la taille",
        "product.size": "Taille",
        "product.color": "Couleur",
        "product.quantity": "Quantité",
        "product.key_benefits": "Avantages clés",
        "product.size_guide": "Guide des tailles",
        "product.you_may_also_like": "Vous pourriez aussi aimer",
        "product.not_found": "Produit non trouvé",
        "product.return_home": "Retour à l'accueil",
        "product.select_color": "Sélectionner la couleur",
        "product.related_description": "Découvrez ces pièces complémentaires soigneusement sélectionnées de notre collection.",
        "product.view_all": "Voir tous les produits",
        "product.each": "pièce",
        "breadcrumb.home": "Accueil",
        "breadcrumb.shop": "Boutique",
        "cart.discount_label": "Réduction (20%)",
        "cart.announcement": "Livraison gratuite à partir de 750 MAD • Utilisez le code ARGAN20 pour 20% de réduction",
        "cart.your_cart_empty": "Votre panier est vide",
        "cart.empty_desc": "Il semble que vous n'ayez pas encore ajouté d'articles à votre panier.",
        "cart.start_shopping": "Commencer les achats",
        "cart.shopping_cart": "Panier",
        "cart.items": "articles",
        "cart.order_summary": "Résumé de la commande",
        "cart.subtotal": "Sous-total",
        "cart.shipping": "Livraison",
        "cart.free": "Gratuit",
        "cart.total": "Total",
        "cart.proceed_checkout": "Passer à la caisse",
        "cart.promo_code": "Code promo",
        "cart.apply": "Appliquer",
        "cart.applied": "Appliqué",
        "cart.enter_code": "Entrer le code",
        "cart.discount_applied": "réduction appliquée !",
        "cart.add_more_shipping": "Ajoutez plus pour la livraison gratuite",
        "cart.continue_shopping": "Continuer les achats",
        "cart.trust.shipping": "Livraison gratuite à partir de 750 MAD",
        "cart.trust.secure": "Paiement sécurisé",
        "cart.trust.returns": "Retours sous 30 jours",

        // FAQ
        "faq.title": "Questions fréquemment posées",
        "faq.subtitle": "Tout ce que vous devez savoir sur nos vêtements et notre service.",
        "faq.q1": "Comment choisir la bonne taille ?",
        "faq.a1": "Vous trouverez un guide des tailles détaillé sur chaque page produit. Si vous êtes entre deux tailles, nous recommandons généralement de prendre la taille supérieure pour une coupe plus décontractée.",
        "faq.q2": "Combien de temps prend la livraison ?",

        // Common Statuses
        "status.all": "Tout",
        "status.processing": "Traitement",
        "status.delivered": "Livré",
        "status.pending": "En attente",
        "status.cancelled": "Annulé",
        "status.shipped": "Expédié",
        "status.sale": "Vendu",
        "source.pos": "POS",
        "source.online": "E-Commerce",

        "faq.a2": "Nous offrons une livraison rapide ! Les commandes locales arrivent généralement en 2 à 4 jours ouvrables. Les commandes internationales arrivent généralement dans les 5 à 8 jours ouvrables.",
        "faq.q3": "Quelle est votre politique de retour ?",
        "faq.a3": "Si quelque chose ne vous convient pas, vous pouvez retourner les articles non portés avec leurs étiquettes dans les 14 jours suivant la livraison pour un échange ou un remboursement, selon notre politique.",
        "faq.q4": "Un article sera-t-il réapprovisionné ?",
        "faq.a4": "Certaines de nos pièces sont des séries limitées. Si un article est épuisé, vous pouvez rejoindre la liste d'attente sur la page produit et nous vous avertirons s'il revient.",

        "faq.q5": "Comment dois-je entretenir mes pièces Azana ?",
        "faq.a5": "La plupart des articles peuvent être lavés en machine à cycle délicat à l'eau froide et séchés à l'air. Vérifiez toujours l'étiquette d'entretien sur chaque vêtement pour des instructions spécifiques.",
        "faq.q6": "Puis-je modifier ou annuler ma commande ?",
        "faq.a6": "Nous commençons à préparer votre commande rapidement, mais vous pouvez nous contacter dès que possible et nous ferons de notre mieux pour la mettre à jour ou l'annuler avant l'expédition.",

        // Admin Navigation
        "admin.nav.dashboard": "Tableau de bord",
        "admin.nav.pos": "Caisse (POS)",
        "admin.nav.orders": "Commandes",
        "admin.nav.products": "Produits",
        "admin.nav.inventory": "Stock",
        "admin.nav.customers": "Clients",
        "admin.nav.analytics": "Analyses",
        "admin.nav.carousel": "Carrousel",
        "admin.nav.whatsapp": "Prospects WhatsApp",
        "admin.nav.contacts": "Messages",
        "admin.nav.careers": "Candidatures",
        "admin.nav.settings": "Paramètres",
        "admin.nav.logout": "Déconnexion",

        // Admin Dashboard
        "admin.dashboard.title": "Tableau de bord",
        "admin.dashboard.subtitle": "Vue d'ensemble détaillée",
        "admin.dashboard.search": "Rechercher...",

        // Admin Login
        "admin.login.title": "Accès Admin",
        "admin.login.subtitle": "Entrez votre code PIN sécurisé",
        "admin.login.authorized": "Personnel autorisé uniquement",
        "admin.login.invalid": "PIN invalide",
        "admin.login.access_granted": "Accès autorisé",

        // Admin Stats & Recent Orders
        "admin.stats.total_revenue": "Revenu total",
        "admin.stats.total_orders": "Total des commandes",
        "admin.stats.total_products": "Total des produits",
        "admin.stats.total_customers": "Total des clients",
        "admin.stats.active": "Actif",
        "admin.stats.sync": "Synchronisation",
        "admin.recent_orders.title": "Commandes récentes",
        "admin.recent_orders.view_all": "Voir tout",
        "admin.recent_orders.order_id": "ID Commande",
        "admin.recent_orders.customer": "Client",
        "admin.recent_orders.email": "Email",
        "admin.recent_orders.amount": "Montant",
        "admin.recent_orders.status": "Statut",
        "admin.recent_orders.action": "Action",
        "admin.recent_orders.loading": "Chargement...",
        "admin.recent_orders.empty": "Aucune commande récente.",

        // Admin Customers
        "admin.customers.title": "Clients",
        "admin.customers.subtitle": "Gérer votre base de clients",
        "admin.customers.export": "Exporter",
        "admin.customers.filters": "Filtres",
        "admin.customers.search": "Rechercher des clients...",
        "admin.customers.total_customers": "Total Clients",
        "admin.customers.active_customers": "Clients Actifs",
        "admin.customers.table_customer": "Client",
        "admin.customers.table_orders": "Commandes",
        "admin.customers.table_spent": "Total Dépensé",
        "admin.customers.table_joined": "Date d'inscription",
        "admin.customers.no_customers": "Aucun client trouvé.",
        "admin.customers.loading": "Chargement des clients...",

        // Admin Products
        "admin.products.title": "Produits",
        "admin.products.manage_inventory": "Gérez votre inventaire",
        "admin.products.manage_categories": "Gérer les catégories",
        "admin.products.category_name_placeholder": "Nom de la catégorie",
        "admin.products.confirm_delete_category": "Supprimer cette catégorie ? Les produits l'utilisant devront être recatégorisés.",
        "admin.products.confirm_delete_product": "Êtes-vous sûr de vouloir supprimer ce produit ?",
        "admin.products.error_adding_category": "Erreur lors de l'ajout de la catégorie",
        "admin.products.error_deleting_category": "Erreur lors de la suppression de la catégorie",
        "admin.products.category_deleted_success": "Catégorie supprimée avec succès",
        "admin.products.error_deleting_product": "Erreur lors de la suppression du produit",
        "admin.products.add_product": "Ajouter un produit",
        "admin.products.total_products": "Total Produits",
        "admin.products.total_inventory": "Inventaire Total",
        "admin.products.low_stock": "Stock Faible",
        "admin.products.out_of_stock": "Rupture de Stock",
        "admin.products.new_arrival": "Nouvel Arrivage",
        "admin.products.discard": "Annuler",
        "admin.products.publish": "Publier le produit",
        "admin.products.basic_info": "Informations de base",
        "admin.products.essential": "Essentiel",
        "admin.products.product_title": "Titre du produit",
        "admin.products.title_placeholder": "ex. Huile d'Argan Pure Rateb",
        "admin.products.description": "Description",
        "admin.products.description_placeholder": "Description en anglais",
        "admin.products.media_gallery": "Galerie Média",
        "admin.products.upload_image": "Télécharger Image",
        "admin.products.specifics": "Spécificités",
        "admin.products.key_benefits": "Avantages Clés",
        "admin.products.benefit_placeholder": "Description de l'avantage (Anglais)",
        "admin.products.no_benefits": "Aucun avantage ajouté.",
        "admin.products.size_guide": "Guide des tailles",
        "admin.products.status": "Statut",
        "admin.products.status_draft": "Brouillon",
        "admin.products.status_active": "Actif",
        "admin.products.category": "Catégorie",
        "admin.products.select_category": "Sélectionner une catégorie",
        "admin.products.product_type": "Type de produit",
        "admin.products.product_type_placeholder": "ex. Sérum",
        "admin.products.pricing": "Prix",
        "admin.products.price": "Prix (MAD)",
        "admin.products.compare_at": "Prix comparatif (Optionnel)",
        "admin.products.inventory": "Inventaire",
        "admin.products.stock": "Stock",
        "admin.products.sku": "SKU",
        "admin.products.auto_generated": "Généré automatiquement",
        "admin.products.cross_sells": "Ventes croisées",
        "admin.products.auto_select": "Sélection Auto",
        "admin.products.recommended_desc": "Produits recommandés basés sur la description.",
        "admin.products.uploading": "Téléchargement...",
        "admin.products.polish": "Améliorer",
        "admin.products.edit_title": "Modifier le produit",
        "admin.products.edit_subtitle": "Mettre à jour les informations du produit",
        "admin.products.save_changes": "Enregistrer les modifications",
        "admin.products.saving": "Enregistrement...",
        "admin.products.loading_product": "Chargement du produit...",
        "admin.products.general_info": "Informations générales",
        "admin.products.product_attributes": "Attributs du produit",
        "admin.products.product_media": "Médias du produit",
        "admin.products.images_count": "Images",
        "admin.products.primary": "Principal",
        "admin.products.upload": "Télécharger",
        "admin.products.organization": "Organisation",
        "admin.products.select_category_placeholder": "Sélectionner une catégorie",
        "admin.products.pricing_section": "Tarification",
        "admin.products.price_mad": "Prix (MAD)",
        "admin.products.compare_at_price": "Prix comparatif (Optionnel)",
        "admin.products.inventory_stock_section": "Stock",
        "admin.products.stock_quantity": "Quantité en stock",
        "admin.products.sku_label": "SKU",
        "admin.products.generate_sku": "Générer SKU",
        "admin.products.variants_section": "Variantes du produit (Tailles et Couleurs)",
        "admin.products.add_variant": "Ajouter une variante",
        "admin.products.select_sizes": "1. Sélectionner les tailles",
        "admin.products.select_colors": "2. Sélectionner les couleurs",
        "admin.products.multiple": "Multiple",
        "admin.products.visual_selection": "Sélection visuelle",
        "admin.products.generate_combinations": "Générer {count} combinaisons",
        "admin.products.active_variants": "Variantes actives ({count})",
        "admin.products.no_variants": "Aucune variante ajoutée pour le moment.",
        "admin.products.variant_size": "Taille",
        "admin.products.variant_color": "Couleur",
        "admin.products.variant_price": "Prix (MAD)",
        "admin.products.variant_stock": "Stock",
        "admin.products.add_benefit_button": "Ajouter un avantage",
        "admin.products.no_benefits_message": "Aucun avantage ajouté pour le moment. Mettez en valeur ce qui rend ce produit spécial.",
        "admin.products.size_guide_label": "Guide des tailles / Informations supplémentaires",
        "admin.products.size_guide_placeholder": "Ajouter des mesures de taille ou des instructions spécifiques au produit...",
        "admin.products.error_title_required": "Veuillez saisir un titre de produit",
        "admin.products.error_category_required": "Veuillez sélectionner une catégorie",
        "admin.products.error_price_required": "Veuillez saisir un prix valide",
        "admin.products.error_updating": "Erreur lors de la mise à jour du produit : {message}",
        "admin.products.error_uploading": "Erreur lors du téléchargement des images",
        "admin.products.improve_ai": "Améliorer avec l'IA",
        "admin.products.ai_quota_exceeded": "⚠️ Quota AI gratuit quotidien dépassé\\n\\nVeuillez attendre demain ou ajouter votre propre clé OpenRouter dans les paramètres.",
        "admin.products.published_title": "Publié !",
        "admin.products.published_redirect": "Redirection vers les produits...",
        "admin.products.publishing_title": "Publication du produit",
        "admin.products.publishing_desc": "Optimisation des images & synchronisation...",
        "admin.products.table_actions": "Actions",
        "admin.products.not_found": "Aucun produit trouvé.",
        "admin.products.units": "unités",

        // Admin Orders Page
        "admin.orders.title": "Commandes",
        "admin.orders.subtitle": "Gérer et suivre les commandes",
        "admin.orders.search_placeholder": "Rechercher des commandes...",
        "admin.orders.table.order": "Commande",
        "admin.orders.table.date": "Date",
        "admin.orders.table.customer": "Client",
        "admin.orders.table.items": "Articles",
        "admin.orders.table.total": "Total",
        "admin.orders.table.source": "Source",
        "admin.orders.table.status": "Statut",
        "admin.orders.table.actions": "Actions",
        "admin.orders.loading": "Chargement des commandes...",
        "admin.orders.not_found": "Aucune commande trouvée correspondant à vos critères",
        "admin.orders.pagination": "Affichage de {start}-{end} sur {total} commandes",

        // Admin Order Details
        "admin.order.loading": "Chargement des détails de la commande...",
        "admin.order.not_found": "Commande non trouvée",
        "admin.order.go_back": "Retour",
        "admin.order.print_invoice": "Imprimer la facture",
        "admin.order.order_items": "Articles de la commande",
        "admin.order.qty": "Qté",
        "admin.order.subtotal": "Sous-total",
        "admin.order.shipping": "Livraison",
        "admin.order.total": "Total",
        "admin.order.store_name": "AZANA BOUTIQUE",
        "admin.order.store_tagline": "Boutique & Vêtements de Luxe",
        "admin.order.morocco": "Maroc",
        "admin.order.update_status": "Mettre à jour le statut",
        "admin.order.status.pending": "En attente",
        "admin.order.status.processing": "En traitement",
        "admin.order.status.shipped": "Expédié",
        "admin.order.status.delivered": "Livré",
        "admin.order.status.cancelled": "Annulé",
        "admin.order.customer": "Client",
        "admin.order.email": "Email",
        "admin.order.phone": "Téléphone",
        "admin.order.address": "Adresse",
        "admin.order.delivery_info": "Informations de livraison",
        "admin.order.method": "Méthode",
        "admin.order.standard_delivery": "Livraison standard",
        "admin.order.destination": "Destination",
        "admin.order.payment": "Paiement",
        "admin.order.cod": "Paiement à la livraison (COD)",
        "admin.order.payment_collected": "Paiement collecté",
        "admin.order.payment_pending": "Paiement en attente",
        "admin.order.paid": "Payé",
        "admin.order.printing": "Impression de la facture...",
        "admin.order.status_updated": "Statut de la commande mis à jour",
        "admin.order.status_update_failed": "Échec de la mise à jour du statut",
        "admin.order.pos_sale": "VENTE POS",
        "admin.order.date": "Date",
        "admin.order.items": "Articles",
        "admin.order.print_receipt": "Reçu de commande",
        "admin.order.thanks": "MERCI DE VOTRE VISITE !",
        "admin.order.returns_policy": "Les retours sont acceptés sous 15 jours.",
        "admin.order.client": "CLIENT",
        "admin.order.product": "PRODUIT",
        "admin.order.price": "PRIX",
        "admin.order.email_label": "EMAIL",
        "admin.order.phone_label": "TÉLÉPHONE",
        "admin.order.address_label": "ADRESSE",
        "admin.order.method_label": "MÉTHODE",
        "admin.order.dest_label": "DESTINATION",
        "admin.order.payment_label": "PAIEMENT",

        // Admin Settings
        "admin.settings.title": "Paramètres du magasin",
        "admin.settings.subtitle": "Gérez les informations de votre magasin, les textes promotionnels et les configurations système.",
        "admin.settings.reset": "Réinitialiser",
        "admin.settings.save": "Enregistrer",
        "admin.settings.saved": "Paramètres enregistrés avec succès",
        "admin.settings.save_failed": "Échec de l'enregistrement des paramètres",
        "admin.settings.store_info": "Informations du magasin",
        "admin.settings.store_name": "Nom du magasin",
        "admin.settings.support_email": "Email de support",
        "admin.settings.store_name_placeholder": "Entrez le nom de la boutique",
        "admin.settings.support_email_placeholder": "support@exemple.com",
        "admin.settings.currency": "Devise",
        "admin.settings.promotions": "Promotions et textes",
        "admin.settings.announcement_bar": "Barre d'annonce",
        "admin.settings.announcement_bar_ar": "Barre d'annonce (Arabe)",
        "admin.settings.promo_code": "Code promo",
        "admin.settings.hero_title": "Titre principal",
        "admin.settings.hero_subtitle": "Sous-titre principal",
        "admin.settings.hero_title_ar": "Titre principal (Arabe)",
        "admin.settings.hero_subtitle_ar": "Sous-titre principal (Arabe)",
        "admin.settings.whatsapp_contact": "WhatsApp et contact",
        "admin.settings.whatsapp_number": "Numéro WhatsApp",
        "admin.settings.contact_phone": "Téléphone de contact",
        "admin.settings.admin_security": "Sécurité admin",
        "admin.settings.admin_pin": "Code PIN admin",
        "admin.settings.admin_pin_desc": "utilisé pour la vérification d'accès au tableau de bord",
        "admin.settings.system_notifications": "Notifications système",
        "admin.settings.push_notifications": "Notifications push mobile",
        "admin.settings.push_notifications_desc": "Recevez des alertes en temps réel pour les nouvelles commandes sur votre appareil mobile.",
        "admin.settings.device_status": "État de l'appareil",
        "admin.settings.device_status_desc": "Abonnez votre téléphone/PC actuel pour recevoir des alertes.",
        "admin.settings.subscribe_device": "Abonner l'appareil",
        "admin.settings.test_notification": "Envoyer une notification test",
        "admin.settings.mobile_requirements": "Exigences mobiles",
        "admin.settings.android_info": "Android: Fonctionne dans Chrome moderne.",
        "admin.settings.ios_info": "iOS (iPhone): Vous DEVEZ d'abord \"Ajouter à l'écran d'accueil\".",
        "admin.settings.device_specific": "Les abonnements sont spécifiques à l'appareil; vous devez les activer sur chaque téléphone.",
        "admin.settings.test_sent": "Envoyé à {count} appareil(s)",
        "admin.settings.no_subscriptions": "Aucun abonnement actif trouvé pour ce magasin.",
        "admin.settings.test_failed": "Échec de l'envoi de la notification test",


        // Checkout
        "checkout.title": "Paiement",
        "checkout.contact_info": "Informations de contact",
        "checkout.full_name": "Nom complet",
        "checkout.phone": "Numéro de téléphone",
        "checkout.email": "Email (optionnel)",
        "checkout.city": "Ville",
        "checkout.address": "Adresse",
        "checkout.pay": "Payer",
        "checkout.processing": "Traitement en cours...",
        "checkout.success_title": "Commande confirmée !",
        "checkout.success_desc": "Nous avons reçu votre commande. Nous vous appellerons sous peu pour confirmer les détails.",
        "checkout.continue_shopping": "Continuer les achats",
        "checkout.cancel_title": "Paiement annulé",
        "checkout.cancel_desc": "Votre paiement a été annulé. Aucun frais n'a été facturé.",
        "checkout.return_cart": "Retour au panier",
        "checkout.retry": "Réessayer le paiement",
        "checkout.select_city": "Sélectionnez une ville",
        "checkout.address_placeholder": "Adresse de rue, appartement, suite, etc.",
        "checkout.error": "Échec du traitement du paiement. Veuillez réessayer.",
        "validation.required": "Ce champ est obligatoire",
        "validation.phone": "Veuillez entrer un numéro de téléphone valide (min 9 caractères)",
        "validation.email": "Veuillez entrer une adresse email valide",

        // Success Page
        "success.thank_you": "Merci",
        "success.order_confirmed": "Votre commande est confirmée",
        "success.coupon_title": "Un cadeau spécial pour vous",
        "success.coupon_desc": "Utilisez ce code pour 20% de réduction sur votre prochain achat",
        "success.order_summary": "Résumé de la commande",
        "footer.about_desc": "Azana est une marque de vêtements féminins de luxe et de boutique, proposant des robes et des pièces quotidiennes qui sont sans effort, féminines et intemporelles.",
        "footer.privacy_short": "Confidentialité",
        "footer.terms_short": "Conditions",
        "footer.system_status": "Système normal",

        // WhatsApp
        "whatsapp.title": "Recevez les mises à jour de style sur WhatsApp",
        "whatsapp.desc": "Rejoignez notre liste VIP pour des réductions exclusives, des idées de style et un accès prioritaire aux nouvelles collections.",
        "whatsapp.placeholder": "Numéro de téléphone",
        "whatsapp.button": "Rejoindre maintenant",
        "whatsapp.success_title": "Vous êtes sur la liste !",
        "whatsapp.success_desc": "Merci de vous être abonné. Nous avons envoyé un cadeau de bienvenue sur votre WhatsApp.",
        "whatsapp.disclaimer": "En vous inscrivant, vous acceptez de recevoir des messages marketing sur WhatsApp. Désinscrivez-vous à tout moment.",
        "whatsapp.register_another": "Enregistrer un autre numéro",
        "whatsapp.verified_updates": "Mises à jour WhatsApp vérifiées",
        "whatsapp.processing": "Traitement en cours...",

        // Timer
        "timer.days": "Jours",
        "timer.hours": "Heures",
        "timer.minutes": "Minutes",
        "timer.seconds": "Secondes",
        "timer.loading": "Chargement des produits...",

        // Accessibility
        "accessibility.go_to_slide": "Aller à la diapositive",

        // Admin Inventory
        "admin.inventory.title": "Gestion du Stock",
        "admin.inventory.sync": "Synchroniser",
        "admin.inventory.search_placeholder": "Rechercher par titre ou SKU...",
        "admin.inventory.filter_all": "Tout",
        "admin.inventory.filter_low": "Faible",
        "admin.inventory.filter_out": "Épuisé",
        "admin.inventory.table_product": "Produit",
        "admin.inventory.table_sku": "SKU Principal",
        "admin.inventory.table_stock": "Stock Global",
        "admin.inventory.table_actions": "Actions",
        "admin.inventory.loading": "Chargement de l'inventaire...",
        "admin.inventory.no_products": "Aucun produit trouvé",
        "admin.inventory.add_variant": "Ajouter Variant",
        "admin.inventory.preselect_all": "Tout Sélectionner",
        "admin.inventory.stock_status_in": "En Stock",
        "admin.inventory.stock_status_low": "Stock Faible",
        "admin.inventory.stock_status_out": "Rupture de Stock",
        "admin.inventory.variants_count": "{count} Variants",
        "admin.inventory.toast_labels_prepared": "{count} étiquettes préparées pour l'export PDF.",
        "admin.inventory.toast_stock_updated": "Stock mis à jour avec succès",
        "admin.inventory.toast_stock_failed": "Échec de la mise à jour du stock",
        "admin.inventory.print_barcodes": "Imprimer Barcodes ({count})",
        "admin.inventory.export_barcodes": "Exporter tous les Barcodes",

        // Admin Inventory Dialog
        "admin.inventory.dialog.add_title": "Ajouter une variante",
        "admin.inventory.dialog.size": "Taille",
        "admin.inventory.dialog.color": "Couleur",
        "admin.inventory.dialog.price": "Prix (MAD)",
        "admin.inventory.dialog.stock": "Stock Initial",
        "admin.inventory.dialog.sku_auto": "Généré automatiquement si vide",
        "admin.inventory.dialog.print_label": "Imprimer l'étiquette SKU",
        "admin.inventory.dialog.print_desc": "L'étiquette sera générée après la création",
        "admin.inventory.dialog.submit": "Créer la variante",
        "admin.inventory.dialog.validation_error": "Veuillez fournir au moins une taille ou une couleur",

        // Admin POS
        "admin.pos.title": "Terminal Point de Vente",
        "admin.pos.subtitle": "Gérer les ventes et le stock",
        "admin.pos.search_placeholder": "Rechercher des produits...",
        "admin.pos.category_all": "Tout",
        "admin.pos.no_products": "Aucun produit trouvé",
        "admin.pos.clear_filters": "Effacer les filtres",
        "admin.pos.view_cart": "Voir le panier",
        "admin.pos.items": "articles",
        "admin.pos.all_categories": "Toutes les catégories",
        "admin.pos.search_products": "Rechercher des produits",
        "admin.pos.generating_ticket": "Génération du ticket",
        "admin.pos.printing_in_progress": "Impression en cours...",
        "admin.pos.cart_title": "Panier",
        "admin.pos.receipt_no": "N° de Reçu",
        "admin.pos.type": "Type",
        "admin.pos.pos_transaction": "TRANSACTION POS",
        "admin.pos.tax": "Taxe",
        "admin.pos.current_cart": "Panier actuel",
        "admin.pos.items_selected": "articles sélectionnés",
        "admin.pos.empty_cart": "Le panier attend vos articles...",
        "admin.pos.grand_total": "Total général",
        "admin.pos.print_complete": "Imprimer & Terminer",
        "admin.pos.view_cart_details": "Voir les détails du panier",
        "admin.pos.view_cart_complete": "Voir le panier & Terminer",
        "admin.pos.walkin_customer": "Client POS",
        "admin.pos.store_city": "Rabat",
        "admin.pos.order_success": "Commande terminée avec succès !",
        "admin.pos.checkout_error": "Échec de la commande. Veuillez réessayer.",
    },
    ar: {
        "common.currency": "د.م",
        "common.size": "المقاس",
        "common.color": "اللون",
        "common.morocco": "المغرب",
        // Navigation
        "nav.shop": "المتجر",
        "nav.collections": "المجموعات",
        "nav.about": "من نحن",
        "nav.faq": "أسئلة شائعة",
        "nav.search": "بحث",
        "nav.shop_now": "تسوق الآن",
        "nav.view_all_collections": "عرض كل المجموعات",

        // Header Popups
        "header.categories": "الأقسام",
        "header.browse_by_category": "تصفح حسب القسم",
        "header.face_care": "العناية بالوجه",
        "header.face_care_desc": "سيروم، كريمات وزيوت",
        "header.hair_care": "العناية بالشعر",
        "header.hair_care_desc": "علاجات وأقنعة",
        "header.body_care": "العناية بالجسم",
        "header.body_care_desc": "لوشن وزبدة الجسم",
        "header.gift_sets": "مجموعات الهدايا",
        "header.gift_sets_desc": "باقات مختارة",
        "header.new_arrival": "وصل حديثاً",
        "header.argan_elixir": "إكسير الأرغان للشعر",
        "header.argan_elixir_desc": "تركيبة ثورية لشعر ناعم كالحرير",
        "header.signature": "المميزة",
        "header.essentials": "الأساسية",
        "header.premium": "الفاخرة",

        // Hero
        "hero.title_prefix": "أناقة",
        "hero.title_suffix": "المرأة العصرية",
        "hero.subtitle": "اكتشفي أزياء نسائية فاخرة من الفساتين إلى الإطلالات اليومية، بتصاميم مريحة وتفاصيل أنثوية مميزة.",
        "hero.shop_collection": "تسوقي المجموعة",
        "hero.explore_best_sellers": "استكشفي الأكثر مبيعاً",
        "hero.fast_delivery": "توصيل سريع",
        "hero.secure_checkout": "دفع آمن",
        "hero.easy_returns": "إرجاع سهل",
        "hero.pure_argan_oil": "زيت أرغان نقي",
        "hero.cold_pressed": "معصور على البارد",

        // Sections
        "section.featured_collections": "مجموعات مميزة",
        "section.featured_desc": "استكشفي مجموعاتنا المختارة من الفساتين والقطع الأساسية والإطلالات الكاملة.",
        "section.certifications": "معايير للجودة والراحة",
        "section.best_sellers": "الأقسام",
        "section.best_sellers_desc": "استعرضي جميع أقسام الملابس لدينا.",
        "section.all_categories": "الكل",
        "section.view_all_products": "عرض كل المنتجات",
        "section.load_more": "تحميل المزيد",
        "section.why_choose": "لماذا تختارين أزانا؟",
        "section.organic": "خامات فاخرة",
        "section.organic_desc": "أقمشة ناعمة وعملية مختارة بعناية لراحتك طوال اليوم.",
        "section.award_winning": "قصّات مريحة وجذابة",
        "section.award_winning_desc": "تصاميم تبرز جمالك وتناسب أسلوب حياتك.",
        "section.cruelty_free": "تصميم واعٍ",
        "section.cruelty_free_desc": "قطع يمكنك ارتداؤها بطرق مختلفة ومواسم متتالية.",
        "section.handcrafted": "لمسات بوتيك خاصة",
        "section.handcrafted_desc": "تفاصيل دقيقة تضيف لمسة فخامة لكل إطلالة.",
        "section.limited_offer": "عرض لفترة محدودة",
        "section.promo_title": "خصم 25% على أول إطلالة",
        "section.promo_desc": "ابدئي خزانتك من أزانا بخصم 25%. استخدمي الكود WELCOME25 عند الدفع.",
        "section.get_offer": "احصلي على العرض",
        "section.hurry_up": "سارعي!",
        "section.view_collection": "شفي المجموعة",

        // Newsletter
        "newsletter.title": "ابقي على اطلاع بأحدث الإطلالات",
        "newsletter.desc": "اشتركي ليصلك أحدث المجموعات، أفكار التنسيق، والعروض الحصرية.",
        "newsletter.placeholder": "أدخلي بريدك الإلكتروني",
        "newsletter.subscribe": "اشترك",
        "newsletter.disclaimer": "بالاشتراك، أنت توافقين على سياسة الخصوصية الخاصة بنا. يمكنك إلغاء الاشتراك في أي وقت.",

        // WhatsApp
        "whatsapp.title": "احصلي على آخر الإطلالات عبر واتساب",
        "whatsapp.desc": "انضمي لقائمتنا المميزة ليصلك خصومات حصرية، أفكار تنسيق، وأولوية الوصول للمجموعات الجديدة مباشرة على هاتفك.",
        "whatsapp.placeholder": "رقم الهاتف",
        "whatsapp.button": "انضمي الآن",
        "whatsapp.success_title": "أهلاً بك في القائمة!",
        "whatsapp.success_desc": "شكراً لاشتراكك. أرسلنا لك هدية ترحيبية على واتساب.",
        "whatsapp.disclaimer": "بالانضمام، أنت توافقين على استقبال رسائل تسويقية على واتساب. يمكنك إلغاء الاشتراك في أي وقت.",


        // Footer
        "footer.company": "الشركة",
        "footer.support": "الدعم",
        "footer.legal": "قانوني",
        "footer.our_story": "قصتنا",
        "footer.sustainability": "الاستدامة",


        "footer.contact_us": "اتصل بنا",
        "footer.shipping_info": "معلومات الشحن",

        "footer.privacy_policy": "سياسة الخصوصية",
        "footer.terms": "شروط الخدمة",
        "footer.refund_policy": "سياسة الاسترجاع",
        "footer.cookies": "ملفات تعريف الارتباط",
        "footer.rights": "جميع الحقوق محفوظة.",
        "footer.about_desc": "أزانا علامة أزياء نسائية تقدم قطع بوتيك فاخرة تجمع بين الراحة والأناقة وتمنحك إطلالات مميزة في كل مناسبة.",
        "footer.privacy_short": "الخصوصية",
        "footer.terms_short": "الشروط",
        "footer.system_status": "النظام يعمل",

        // Product & Cart
        "product.add_to_cart": "أضف إلى السلة",
        "product.reviews": "مراجعات",
        "product.in_stock": "متوفر",
        "product.out_of_stock": "غير متوفر",
        "product.select_size": "اختاري المقاس",
        "product.size": "المقاس",
        "product.color": "اللون",
        "product.quantity": "الكمية",
        "product.key_benefits": "الفوائد الرئيسية",
        "product.size_guide": "دليل المقاسات",
        "product.you_may_also_like": "قد يعجبك أيضاً",
        "product.not_found": "المنتج غير موجود",
        "product.return_home": "العودة للرئيسية",
        "product.select_color": "اختاري اللون",
        "product.related_description": "اكتشفي هذه القطع المكملة المختارة بعناية من مجموعتنا.",
        "product.view_all": "عرض جميع المنتجات",
        "product.each": "للقطعة",
        "breadcrumb.home": "الرئيسية",
        "breadcrumb.shop": "المتجر",
        "cart.discount_label": "خصم (20%)",
        "cart.announcement": "شحن مجاني للطلبات فوق 750 د.م • استخدمي كود ARGAN20 لخصم 20%",
        "cart.your_cart_empty": "سلة التسوق فارغة",
        "cart.empty_desc": "يبدو أنك لم تضف أي منتجات إلى سلتك بعد.",
        "cart.start_shopping": "ابدأ التسوق",
        "cart.shopping_cart": "سلة التسوق",
        "cart.items": "منتجات",
        "cart.order_summary": "ملخص الطلب",
        "cart.subtotal": "المجموع الفرعي",
        "cart.shipping": "الشحن",
        "cart.free": "مجاني",
        "cart.total": "المجموع",
        "cart.proceed_checkout": "إتمام الشراء",
        "cart.promo_code": "كود الخصم",
        "cart.apply": "تطبيق",
        "cart.applied": "تم التطبيق",
        "cart.enter_code": "أدخل الكود",
        "cart.discount_applied": "تم تطبيق الخصم!",
        "cart.add_more_shipping": "أضف المزيد للحصول على شحن مجاني",
        "cart.continue_shopping": "مواصلة التسوق",
        "cart.trust.shipping": "شحن مجاني فوق 750 د.م",
        "cart.trust.secure": "دفع آمن",
        "cart.trust.returns": "إرجاع خلال 30 يوم",

        // FAQ
        "faq.title": "أسئلة شائعة",
        "faq.subtitle": "كل ما تحتاجين معرفته عن أزياء وخدمة أزانا.",
        "faq.q1": "كيف أختار المقاس المناسب؟",
        "faq.a1": "ستجدين جدول مقاسات مفصل على كل صفحة منتج. إذا كنتِ بين مقاسين، ننصح باختيار المقاس الأكبر لإحساس أكثر راحة.",
        "faq.q2": "كم يستغرق الشحن؟",

        // Common Statuses
        "status.all": "الكل",
        "status.processing": "قيد المعالجة",
        "status.delivered": "تم التوصيل",
        "status.pending": "قيد الانتظار",
        "status.cancelled": "ملغى",
        "status.shipped": "تم الشحن",
        "status.sale": "مباع",
        "source.pos": "نقطة بيع",
        "source.online": "متجر إلكتروني",

        "faq.a2": "نوفر شحن سريع! الطلبات المحلية تصل عادة خلال 2-4 أيام عمل، والطلبات الدولية خلال 5-8 أيام عمل تقريباً.",
        "faq.q3": "ما هي سياسة الاسترجاع؟",
        "faq.a3": "إذا كان المنتج غير مناسب، يمكنك إرجاعه خلال 14 يوماً من الاستلام بشرط أن يكون بحالته الأصلية ومعه التذكرة، وفقاً لسياسة الاسترجاع.",
        "faq.q4": "هل القطع تتكرر أم أنها محدودة؟",
        "faq.a4": "كثير من قطع أزانا تكون بكميات محدودة. إذا نفد مقاسك، يمكنك الانضمام لقائمة الانتظار من صفحة المنتج وسنرسل لك رسالة إذا عاد مرة أخرى.",
        "faq.q5": "كيف أعتني بقطعي من أزانا؟",
        "faq.a5": "معظم القطع يُنصح بغسلها على دورة لطيفة بمياه باردة وتركها تجف في الهواء. دائماً اتبعي تعليمات العناية المكتوبة على كل قطعة.",
        "faq.q6": "هل أستطيع تعديل أو إلغاء طلبي؟",
        "faq.a6": "نبدأ بتحضير الطلبات بسرعة، فإذا كنتِ ترغبين بتعديل أو إلغاء طلبك، اتصلي بنا بأسرع وقت وسنحاول مساعدتك قبل أن يتم شحن الطلب.",

        // Admin Navigation
        "admin.nav.dashboard": "لوحة القيادة",
        "admin.nav.pos": "نقطة البيع",
        "admin.nav.orders": "الطلبات",
        "admin.nav.products": "المنتجات",
        "admin.nav.inventory": "المخزون",
        "admin.nav.customers": "العملاء",
        "admin.nav.analytics": "التحليلات",
        "admin.nav.carousel": "الشريط الإعلاني",
        "admin.nav.whatsapp": "عملاء واتساب",
        "admin.nav.contacts": "الرسائل",
        "admin.nav.careers": "الوظائف",
        "admin.nav.settings": "الإعدادات",
        "admin.nav.logout": "تسجيل الخروج",

        // Admin Dashboard
        "admin.dashboard.title": "لوحة القيادة",
        "admin.dashboard.subtitle": "نظرة عامة مفصلة",
        "admin.dashboard.search": "بحث...",

        // Admin Login
        "admin.login.title": "دخول المسؤول",
        "admin.login.subtitle": "أدخل رمز PIN الآمن",
        "admin.login.authorized": "للموظفين المصرح لهم فقط",
        "admin.login.invalid": "رمز غير صحيح",
        "admin.login.access_granted": "تم السماح بالدخول",

        // Admin Stats & Recent Orders
        "admin.stats.total_revenue": "إجمالي الإيرادات",
        "admin.stats.total_orders": "إجمالي الطلبات",
        "admin.stats.total_products": "إجمالي المنتجات",
        "admin.stats.total_customers": "إجمالي العملاء",
        "admin.stats.active": "نشط",
        "admin.stats.sync": "مزامنة",
        "admin.recent_orders.title": "أحدث الطلبات",
        "admin.recent_orders.view_all": "عرض الكل",
        "admin.recent_orders.order_id": "رقم الطلب",
        "admin.recent_orders.customer": "العميل",
        "admin.recent_orders.email": "البريد الإلكتروني",
        "admin.recent_orders.amount": "المبلغ",
        "admin.recent_orders.status": "الحالة",
        "admin.recent_orders.action": "إجراء",
        "admin.recent_orders.loading": "جاري التحميل...",
        "admin.recent_orders.empty": "لا توجد طلبات حديثة.",

        // Admin Customers
        "admin.customers.title": "العملاء",
        "admin.customers.subtitle": "إدارة قاعدة عملائك",
        "admin.customers.export": "تصدير",
        "admin.customers.filters": "تصفية",
        "admin.customers.search": "بحث عن العملاء...",
        "admin.customers.total_customers": "إجمالي العملاء",
        "admin.customers.active_customers": "العملاء النشطين",
        "admin.customers.table_customer": "العميل",
        "admin.customers.table_orders": "الطلبات",
        "admin.customers.table_spent": "إجمالي المصروفات",
        "admin.customers.table_joined": "تاريخ الانضمام",
        "admin.customers.no_customers": "لم يتم العثور على عملاء.",
        "admin.customers.loading": "جاري تحميل العملاء...",

        // Admin Products
        "admin.products.title": "المنتجات",
        "admin.products.manage_inventory": "إدارة المخزون",
        "admin.products.manage_categories": "إدارة الأقسام",
        "admin.products.category_name_placeholder": "اسم القسم",
        "admin.products.confirm_delete_category": "هل تريد حذف هذا القسم؟ ستحتاج المنتجات التي تستخدمه إلى تصنيف جديد.",
        "admin.products.confirm_delete_product": "هل أنت متأكد من حذف هذا المنتج؟",
        "admin.products.error_adding_category": "خطأ في إضافة القسم",
        "admin.products.error_deleting_category": "خطأ في حذف القسم",
        "admin.products.category_deleted_success": "تم حذف القسم بنجاح",
        "admin.products.error_deleting_product": "خطأ في حذف المنتج",
        "admin.products.add_product": "إضافة منتج",
        "admin.products.total_products": "إجمالي المنتجات",
        "admin.products.total_inventory": "إجمالي المخزون",
        "admin.products.low_stock": "مخزون منخفض",
        "admin.products.out_of_stock": "نفذ المخزون",
        "admin.products.new_arrival": "وصول جديد",
        "admin.products.discard": "إلغاء",
        "admin.products.publish": "نشر المنتج",
        "admin.products.basic_info": "معلومات أساسية",
        "admin.products.essential": "أساسي",
        "admin.products.product_title": "اسم المنتج",
        "admin.products.title_placeholder": "مثال: زيت أركان نقي راتب",
        "admin.products.description": "الوصف",
        "admin.products.description_placeholder": "الوصف بالإنجليزية",
        "admin.products.media_gallery": "معرض الوسائط",
        "admin.products.upload_image": "رفع صورة",
        "admin.products.specifics": "التفاصيل",
        "admin.products.key_benefits": "الفوائد الرئيسية",
        "admin.products.benefit_placeholder": "وصف الفائدة (إنجليزية)",
        "admin.products.no_benefits": "لم يتم إضافة فوائد.",
        "admin.products.size_guide": "دليل المقاسات",
        "admin.products.status": "الحالة",
        "admin.products.status_draft": "مسودة",
        "admin.products.status_active": "نشط",
        "admin.products.category": "القسم",
        "admin.products.select_category": "اختر القسم",
        "admin.products.product_type": "نوع المنتج",
        "admin.products.product_type_placeholder": "مثال: مصل",
        "admin.products.pricing": "التسعير",
        "admin.products.price": "السعر (درهم)",
        "admin.products.compare_at": "السعر المقارن (اختياري)",
        "admin.products.inventory": "المخزون",
        "admin.products.stock": "الكمية",
        "admin.products.sku": "SKU",
        "admin.products.auto_generated": "توليد تلقائي",
        "admin.products.cross_sells": "منتجات مقترحة",
        "admin.products.auto_select": "تحديد تلقائي",
        "admin.products.recommended_desc": "منتجات موصى بها بناءً على الوصف.",
        "admin.products.uploading": "جاري الرفع...",
        "admin.products.polish": "تحسين",
        "admin.products.edit_title": "تعديل المنتج",
        "admin.products.edit_subtitle": "تحديث معلومات المنتج",
        "admin.products.save_changes": "حفظ التغييرات",
        "admin.products.saving": "جاري الحفظ...",
        "admin.products.loading_product": "جاري تحميل المنتج...",
        "admin.products.general_info": "معلومات عامة",
        "admin.products.product_attributes": "خصائص المنتج",
        "admin.products.product_media": "وسائط المنتج",
        "admin.products.images_count": "صور",
        "admin.products.primary": "أساسي",
        "admin.products.upload": "رفع",
        "admin.products.organization": "التنظيم",
        "admin.products.select_category_placeholder": "اختر الفئة",
        "admin.products.pricing_section": "التسعير",
        "admin.products.price_mad": "السعر (د.م)",
        "admin.products.compare_at_price": "سعر المقارنة (اختياري)",
        "admin.products.inventory_stock_section": "المخزون",
        "admin.products.stock_quantity": "كمية المخزون",
        "admin.products.sku_label": "رمز المنتج",
        "admin.products.generate_sku": "إنشاء رمز المنتج",
        "admin.products.variants_section": "متغيرات المنتج (المقاسات والألوان)",
        "admin.products.add_variant": "إضافة متغير",
        "admin.products.select_sizes": "1. اختر المقاسات",
        "admin.products.select_colors": "2. اختر الألوان",
        "admin.products.multiple": "متعدد",
        "admin.products.visual_selection": "اختيار مرئي",
        "admin.products.generate_combinations": "إنشاء {count} تركيبة",
        "admin.products.active_variants": "المتغيرات النشطة ({count})",
        "admin.products.no_variants": "لم تتم إضافة أي متغيرات بعد.",
        "admin.products.variant_size": "المقاس",
        "admin.products.variant_color": "اللون",
        "admin.products.variant_price": "السعر (د.م)",
        "admin.products.variant_stock": "المخزون",
        "admin.products.add_benefit_button": "إضافة ميزة",
        "admin.products.no_benefits_message": "لم تتم إضافة أي ميزات بعد. أبرز ما يجعل هذا المنتج مميزاً.",
        "admin.products.size_guide_label": "دليل المقاسات / معلومات إضافية",
        "admin.products.size_guide_placeholder": "أضف قياسات المقاسات أو تعليمات خاصة بالمنتج...",
        "admin.products.error_title_required": "الرجاء إدخال عنوان المنتج",
        "admin.products.error_category_required": "الرجاء اختيار الفئة",
        "admin.products.error_price_required": "الرجاء إدخال سعر صحيح",
        "admin.products.error_updating": "خطأ في تحديث المنتج: {message}",
        "admin.products.error_uploading": "خطأ في رفع الصور",
        "admin.products.improve_ai": "تحسين بالذكاء الاصطناعي",
        "admin.products.ai_quota_exceeded": "⚠️ تم تجاوز حصة الذكاء الاصطناعي المجانية اليومية\\n\\nالرجاء الانتظار حتى الغد أو إضافة مفتاح OpenRouter الخاص بك في الإعدادات.",
        "admin.products.published_title": "تم النشر!",
        "admin.products.published_redirect": "جاري التحويل للمتجات...",
        "admin.products.publishing_title": "جاري نشر المنتج",
        "admin.products.publishing_desc": "تحسين الصور والمزامنة...",
        "admin.products.table_actions": "إجراءات",
        "admin.products.not_found": "لم يتم العثور على منتجات.",
        "admin.products.units": "وحدات",

        // Admin Orders Page
        "admin.orders.title": "الطلبات",
        "admin.orders.subtitle": "إدارة وتتبع الطلبات",
        "admin.orders.search_placeholder": "بحث في الطلبات...",
        "admin.orders.table.order": "الطلب",
        "admin.orders.table.date": "التاريخ",
        "admin.orders.table.customer": "العميل",
        "admin.orders.table.items": "المنتجات",
        "admin.orders.table.total": "الإجمالي",
        "admin.orders.table.source": "المصدر",
        "admin.orders.table.status": "الحالة",
        "admin.orders.table.actions": "إجراءات",
        "admin.orders.loading": "جاري تحميل الطلبات...",
        "admin.orders.not_found": "لم يتم العثور على طلبات تطابق بحثك",
        "admin.orders.pagination": "عرض {start}-{end} من أصل {total} طلب",

        // Admin Order Details
        "admin.order.loading": "جاري تحميل تفاصيل الطلب...",
        "admin.order.not_found": "الطلب غير موجود",
        "admin.order.go_back": "رجوع",
        "admin.order.print_invoice": "طباعة الفاتورة",
        "admin.order.order_items": "منتجات الطلب",
        "admin.order.qty": "الكمية",
        "admin.order.subtotal": "المجموع الفرعي",
        "admin.order.shipping": "الشحن",
        "admin.order.total": "الإجمالي",
        "admin.order.store_name": "أزانا بوتيك",
        "admin.order.store_tagline": "بوتيك وملابس فاخرة",
        "admin.order.morocco": "المغرب",
        "admin.order.update_status": "تحديث الحالة",
        "admin.order.status.pending": "قيد الانتظار",
        "admin.order.status.processing": "قيد المعالجة",
        "admin.order.status.shipped": "تم الشحن",
        "admin.order.status.delivered": "تم التوصيل",
        "admin.order.status.cancelled": "ملغي",
        "admin.order.customer": "العميل",
        "admin.order.email": "البريد الإلكتروني",
        "admin.order.phone": "الهاتف",
        "admin.order.address": "العنوان",
        "admin.order.delivery_info": "معلومات التوصيل",
        "admin.order.method": "الطريقة",
        "admin.order.standard_delivery": "توصيل عادي",
        "admin.order.destination": "الوجهة",
        "admin.order.payment": "الدفع",
        "admin.order.cod": "الدفع عند الاستلام",
        "admin.order.payment_collected": "تم تحصيل المبلغ",
        "admin.order.payment_pending": "في انتظار الدفع",
        "admin.order.paid": "مدفوع",
        "admin.order.printing": "جاري طباعة الفاتورة...",
        "admin.order.status_updated": "تم تحديث حالة الطلب",
        "admin.order.status_update_failed": "فشل تحديث الحالة",
        "admin.order.pos_sale": "بيع بنقطة بيع",
        "admin.order.date": "التاريخ",
        "admin.order.items": "العناصر",
        "admin.order.print_receipt": "إيصال الطلب",
        "admin.order.thanks": "شكراً لزيارتكم!",
        "admin.order.returns_policy": "يُقبل الإرجاع خلال 15 يوماً.",
        "admin.order.client": "العميل",
        "admin.order.product": "المنتج",
        "admin.order.price": "السعر",
        "admin.order.email_label": "البريد الإلكتروني",
        "admin.order.phone_label": "الهاتف",
        "admin.order.address_label": "العنوان",
        "admin.order.method_label": "الطريقة",
        "admin.order.dest_label": "الوجهة",
        "admin.order.payment_label": "الدفع",

        // Admin Settings
        "admin.settings.title": "إعدادات المتجر",
        "admin.settings.subtitle": "إدارة معلومات المتجر والنصوص الترويجية وإعدادات النظام.",
        "admin.settings.reset": "إعادة تعيين",
        "admin.settings.save": "حفظ التغييرات",
        "admin.settings.saved": "تم حفظ الإعدادات بنجاح",
        "admin.settings.save_failed": "فشل حفظ الإعدادات",
        "admin.settings.store_info": "معلومات المتجر",
        "admin.settings.store_name": "اسم المتجر",
        "admin.settings.store_name_placeholder": "أدخل اسم المتجر",
        "admin.settings.support_email": "بريد الدعم",
        "admin.settings.support_email_placeholder": "support@example.com",
        "admin.settings.currency": "العملة",
        "admin.settings.promotions": "العروض والنصوص",
        "admin.settings.announcement_bar": "شريط الإعلانات",
        "admin.settings.announcement_bar_ar": "شريط الإعلانات (عربي)",
        "admin.settings.promo_code": "كود الخصم",
        "admin.settings.hero_title": "العنوان الرئيسي",
        "admin.settings.hero_subtitle": "العنوان الفرعي",
        "admin.settings.hero_title_ar": "العنوان الرئيسي (عربي)",
        "admin.settings.hero_subtitle_ar": "العنوان الفرعي (عربي)",
        "admin.settings.whatsapp_contact": "واتساب والتواصل",
        "admin.settings.whatsapp_number": "رقم الواتساب",
        "admin.settings.contact_phone": "هاتف التواصل",
        "admin.settings.admin_security": "أمان المسؤول",
        "admin.settings.admin_pin": "رمز PIN المسؤول",
        "admin.settings.admin_pin_desc": "يستخدم للتحقق من الوصول للوحة التحكم",
        "admin.settings.system_notifications": "إشعارات النظام",
        "admin.settings.push_notifications": "إشعارات الهاتف",
        "admin.settings.push_notifications_desc": "استلم تنبيهات فورية للطلبات الجديدة على جهازك.",
        "admin.settings.device_status": "حالة الجهاز",
        "admin.settings.device_status_desc": "اشترك بهاتفك/حاسوبك الحالي لاستلام التنبيهات.",
        "admin.settings.subscribe_device": "اشتراك الجهاز",
        "admin.settings.test_notification": "إرسال إشعار تجريبي",
        "admin.settings.mobile_requirements": "متطلبات الهاتف",
        "admin.settings.android_info": "أندرويد: يعمل في كروم الحديث.",
        "admin.settings.ios_info": "iOS (آيفون): يجب \"إضافة إلى الشاشة الرئيسية\" أولاً.",
        "admin.settings.device_specific": "الاشتراكات خاصة بكل جهاز؛ يجب تفعيلها على كل هاتف.",
        "admin.settings.test_sent": "تم الإرسال إلى {count} جهاز",
        "admin.settings.no_subscriptions": "لا توجد اشتراكات نشطة لهذا المتجر.",
        "admin.settings.test_failed": "فشل إرسال الإشعار التجريبي",

        // Admin POS
        "admin.pos.title": "نقطة البيع (POS)",
        "admin.pos.subtitle": "إدارة المبيعات والمخزون",
        "admin.pos.search_placeholder": "بحث عن المنتجات...",
        "admin.pos.category_all": "الكل",
        "admin.pos.no_products": "لم يتم العثور على منتجات",
        "admin.pos.clear_filters": "مسح التصفية",
        "admin.pos.view_cart": "عرض السلة",
        "admin.pos.items": "منتج",
        "admin.pos.all_categories": "جميع الفئات",
        "admin.pos.search_products": "بحث عن المنتجات",
        "admin.pos.generating_ticket": "جاري إنشاء التذكرة",
        "admin.pos.printing_in_progress": "جاري الطباعة...",
        "admin.pos.cart_title": "سلة التسوق",
        "admin.pos.receipt_no": "رقم الإيصال",
        "admin.pos.type": "النوع",
        "admin.pos.pos_transaction": "عملية نقطة بيع",
        "admin.pos.tax": "الضريبة",
        "admin.pos.current_cart": "السلة الحالية",
        "admin.pos.items_selected": "منتج محدد",
        "admin.pos.empty_cart": "السلة بانتظار منتجات أنيقة...",
        "admin.pos.grand_total": "المجموع الإجمالي",
        "admin.pos.view_cart_details": "عرض تفاصيل السلة",
        "admin.pos.view_cart_complete": "عرض السلة وإتمام",
        "admin.pos.walkin_customer": "زبون نقطة البيع",
        "admin.pos.store_city": "الرباط",
        "admin.pos.print_complete": "طباعة وإتمام",
        "admin.pos.order_success": "تم إكمال الطلب بنجاح!",
        "admin.pos.checkout_error": "فشل إتمام الطلب. يرجى المحاولة مرة أخرى.",


        "checkout.title": "إتمام الطلب",
        "checkout.contact_info": "معلومات الاتصال",
        "checkout.full_name": "الاسم الكامل",
        "checkout.phone": "رقم الهاتف",
        "checkout.email": "البريد الإلكتروني (اختياري)",
        "checkout.city": "المدينة",
        "checkout.address": "العنوان",
        "checkout.pay": "دفع",
        "checkout.processing": "جاري المعالجة...",
        "checkout.success_title": "تم تأكيد الطلب!",
        "checkout.continue_shopping": "مواصلة التسوق",
        "checkout.cancel_title": "تم إلغاء الدفع",
        "checkout.cancel_desc": "تم إلغاء عملية الدفع. لم يتم خصم أي مبلغ.",
        "checkout.return_cart": "العودة للسلة",
        "checkout.retry": "إعادة المحاولة",
        "checkout.select_city": "اختاري المدينة",
        "checkout.address_placeholder": "العنوان الكامل، الشقة، الطابق، إلخ.",
        "checkout.error": "فشل في معالجة الدفع. يرجى المحاولة مرة أخرى.",
        "validation.required": "هذا الحقل مطلوب",
        "validation.phone": "يرجى إدخال رقم هاتف صحيح (أكثر من 9 أرقام)",
        "validation.email": "يرجى إدخال بريد إلكتروني صحيح",

        // Success Page
        "success.thank_you": "شكراً لك",
        "success.order_confirmed": "تم استلام طلبك",
        "checkout.success_desc": "لقد استلمنا طلبك. سنتصل بك قريباً لتأكيد التفاصيل.",
        "success.coupon_title": "هدية خاصة لك",
        "success.coupon_desc": "استخدم هذا الكود لخصم 20% على طلبك القادم",
        "success.order_summary": "ملخص الطلب",

        // WhatsApp New
        "whatsapp.register_another": "تسجيل رقم آخر",
        "whatsapp.verified_updates": "تحديثات واتساب موثقة",
        "whatsapp.processing": "جاري المعالجة...",

        // Timer
        "timer.days": "أيام",
        "timer.hours": "ساعات",
        "timer.minutes": "دقائق",
        "timer.seconds": "ثواني",
        "timer.loading": "جاري تحميل المنتجات...",

        // Accessibility
        "accessibility.go_to_slide": "اذهب للشريحة",

        // Admin Inventory
        "admin.inventory.title": "إدارة المخزون",
        "admin.inventory.sync": "مزامنة",
        "admin.inventory.search_placeholder": "بحث حسب الاسم أو SKU...",
        "admin.inventory.filter_all": "الكل",
        "admin.inventory.filter_low": "منخفض",
        "admin.inventory.filter_out": "نفذ",
        "admin.inventory.table_product": "المنتج",
        "admin.inventory.table_sku": "SKU الرئيسي",
        "admin.inventory.table_stock": "المخزون الإجمالي",
        "admin.inventory.table_actions": "إجراءات",
        "admin.inventory.loading": "جاري تحميل المخزون...",
        "admin.inventory.no_products": "لم يتم العثور على منتجات",
        "admin.inventory.add_variant": "إضافة نوع",
        "admin.inventory.preselect_all": "تحديد الكل",
        "admin.inventory.stock_status_in": "متوفر",
        "admin.inventory.stock_status_low": "مخزون منخفض",
        "admin.inventory.stock_status_out": "نفذ المخزون",
        "admin.inventory.variants_count": "{count} أنواع",
        "admin.inventory.toast_labels_prepared": "تم تجهيز {count} ملصقات للتصدير.",
        "admin.inventory.toast_stock_updated": "تم تحديث المخزون بنجاح",
        "admin.inventory.toast_stock_failed": "فشل تحديث المخزون",
        "admin.inventory.print_barcodes": "طباعة الباركود ({count})",
        "admin.inventory.export_barcodes": "تصدير جميع الباركود",

        // Admin Inventory Dialog
        "admin.inventory.dialog.add_title": "إضافة نوع جديد",
        "admin.inventory.dialog.size": "المقاس",
        "admin.inventory.dialog.color": "اللون",
        "admin.inventory.dialog.price": "السعر (درهم)",
        "admin.inventory.dialog.stock": "المخزون الأولي",
        "admin.inventory.dialog.sku_auto": "سيتم التوليد تلقائياً إذا ترك فارغاً",
        "admin.inventory.dialog.print_label": "طباعة ملصق SKU",
        "admin.inventory.dialog.print_desc": "سيتم إنشاء الملصق بعد الحفظ",
        "admin.inventory.dialog.submit": "إنشاء النوع",
        "admin.inventory.dialog.validation_error": "يرجى تقديم مقاس أو لون على الأقل",
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("fr")

    useEffect(() => {
        // Check localStorage or browser preference on mount
        const savedLang = localStorage.getItem("language")
        if (savedLang === "ar" || savedLang === "fr") {
            setLanguage(savedLang)
        } else {
            // If invalid or 'en', force French and update storage
            setLanguage("fr")
            localStorage.setItem("language", "fr")
        }
    }, [])

    useEffect(() => {
        localStorage.setItem("language", language)

        // Update direction on document
        const dir = language === "ar" ? "rtl" : "ltr"
        document.documentElement.dir = dir
        document.documentElement.lang = language
    }, [language])

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations["fr"]] || key
    }

    const toggleLanguage = () => {
        setLanguage(prev => prev === "fr" ? "ar" : "fr")
    }

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            dir: language === "ar" ? "rtl" : "ltr",
            toggleLanguage
        }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
